apiVersion: apps/v1
kind: Deployment
metadata:
  name: jactrexv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jactrexv
  template:
    metadata:
      labels:
        app: jactrexv
    spec:
      containers:
      - image: okteto.dev/jactrexv:latest
        name: jactrexv
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.videvo.net"
        - name: Vless_UUID
          value: "9cb130cb-53bb-4ece-91ff-1d8909c8c853"
        - name: Vless_Path
          value: "/UHGERDF"
        - name: Vmess_UUID
          value: "9cb130cb-53bb-4ece-91ff-1d8909c8c853"
        - name: Vmess_Path
          value: "/MNRTGSY"
        - name: Share_Path
          value: "/Share043"
