apiVersion: apps/v1
kind: Deployment
metadata:
  name: tweradc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tweradc
  template:
    metadata:
      labels:
        app: tweradc
    spec:
      containers:
      - image: okteto.dev/tweradc:latest
        name: tweradc
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.pexels.com"
        - name: Vless_UUID
          value: "a40dce8c-ee99-4c67-aaa6-ad31d9e96796"
        - name: Vless_Path
          value: "/azxoerhw"
        - name: Vmess_UUID
          value: "a40dce8c-ee99-4c67-aaa6-ad31d9e96796"
        - name: Vmess_Path
          value: "/NBOFTER"
        - name: Share_Path
          value: "/Share244"
