apiVersion: apps/v1
kind: Deployment
metadata:
  name: shaire
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shaire
  template:
    metadata:
      labels:
        app: shaire
    spec:
      containers:
      - image: okteto.dev/shaire:latest
        name: shaire
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.greenmangaming.com"
        - name: Vless_UUID
          value: "85f5615c-025a-4707-a52e-4177462967cc"
        - name: Vless_Path
          value: "/ujdf6y"
        - name: Vmess_UUID
          value: "85f5615c-025a-4707-a52e-4177462967cc"
        - name: Vmess_Path
          value: "/iergdfty"
        - name: Share_Path
          value: "/Share654"
