apiVersion: apps/v1
kind: Deployment
metadata:
  name: cherim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cherim
  template:
    metadata:
      labels:
        app: cherim
    spec:
      containers:
      - image: okteto.dev/cherim:latest
        name: cherim
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "https://www.crazygames.com"
        - name: Vless_UUID
          value: "bcad01e3-25ce-4a6d-97da-71e7f59a67f8"
        - name: Vless_Path
          value: "/ruywdi"
        - name: Vmess_UUID
          value: "bcad01e3-25ce-4a6d-97da-71e7f59a67f8"
        - name: Vmess_Path
          value: "/tbkjtgd"
        - name: Share_Path
          value: "/Share690"
