apiVersion: apps/v1
kind: Deployment
metadata:
  name: actiond
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actiond
  template:
    metadata:
      labels:
        app: actiond
    spec:
      containers:
      - image: okteto.dev/actiond:latest
        name: actiond
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "pixabay.com"
        - name: Vless_UUID
          value: "c8508a96-2c79-4c6b-92ab-af162ca5bd82"
        - name: Vless_Path
          value: "/quyetsdt"
        - name: Vmess_UUID
          value: "c8508a96-2c79-4c6b-92ab-af162ca5bd82"
        - name: Vmess_Path
          value: "/fgqwbor"
        - name: Share_Path
          value: "/Share213"
